// End-to-end tests for the 5 AI moments — clicked through the real UI with
// real OpenRouter calls. Each test creates a small artifact and may rely on
// the cleanup script (server/scripts/cleanup-test-pollution.js) to remove
// junk after a run.
import { expect, test, type APIRequestContext, type Page } from '@playwright/test';

const apiURL = process.env.E2E_API_URL
  || (process.env.E2E_BASE_URL ? `${process.env.E2E_BASE_URL.replace(/\/$/, '')}/api` : 'http://127.0.0.1:4312/api');

type Session = { token: string; user: any };
const sessionCache = new Map<string, Session>();

async function loginApi(request: APIRequestContext, email: string, password: string): Promise<Session> {
  const cached = sessionCache.get(email);
  if (cached) return cached;
  const r = await request.post(`${apiURL}/auth/login`, { data: { email, password } });
  expect(r.ok(), `login failed for ${email}: ${r.status()} ${await r.text()}`).toBeTruthy();
  const session = (await r.json()).data as Session;
  sessionCache.set(email, session);
  return session;
}

async function browserLogin(page: Page, request: APIRequestContext, kind: 'admin' | 'resident') {
  const creds = kind === 'admin'
    ? ['admin@condoos.dev', 'admin123']
    : ['resident@condoos.dev', 'resident123'];
  const s = await loginApi(request, creds[0], creds[1]);
  await page.goto('/', { waitUntil: 'domcontentloaded' });
  await page.evaluate(({ token, user }) => {
    localStorage.setItem('condoos_token', token);
    localStorage.setItem('condoos_user', JSON.stringify(user));
  }, s);
}

// ---------------------------------------------------------------------------
// 1. Resident → Suggest → AI draft → Promote to proposal
// ---------------------------------------------------------------------------

test('AI: resident suggest → AI drafts a proposal → promote', async ({ page, request }) => {
  test.setTimeout(60_000);
  await browserLogin(page, request, 'resident');
  await page.goto('/app/suggest');

  // Type a free-text complaint
  await page.locator('textarea').fill('A iluminação do hall do 3º andar fica piscando à noite, parece que vai apagar a qualquer momento.');

  // Click Submit ("Enviar")
  await page.getByRole('button', { name: /^Enviar$|^Submit$/i }).click();

  // Wait for the AI draft to appear (badge "Proposta redigida pela IA" or "AI-drafted")
  await expect(page.getByText(/Proposta redigida pela IA|AI-drafted proposal/i)).toBeVisible({ timeout: 45_000 });
  // Title generated by AI must be non-empty + reasonable length
  const titleEl = page.locator('h3.font-display').first();
  await expect(titleEl).toBeVisible();
  const title = (await titleEl.textContent() || '').trim();
  expect(title.length, `expected non-empty AI title; got "${title}"`).toBeGreaterThan(5);

  // Promote to proposal button visible (Enviar ao síndico / Send to the board)
  await expect(page.getByRole('button', { name: /Enviar ao síndico|Send to the board/i })).toBeVisible();
});

// ---------------------------------------------------------------------------
// 2. Admin → Cluster suggestions
// ---------------------------------------------------------------------------

test('AI: admin clusters open suggestions', async ({ page, request }) => {
  test.setTimeout(75_000);
  await browserLogin(page, request, 'admin');
  await page.goto('/board/suggestions');

  // The cluster button copy can be EN or PT-BR depending on translation state
  const clusterBtn = page.getByRole('button', { name: /cluster|agrupar/i }).first();
  // It only renders when there are open suggestions; demo has 4 seeded.
  await expect(clusterBtn).toBeVisible({ timeout: 10_000 });
  await clusterBtn.click();

  // Wait for clusters to appear OR a toast confirming success
  // After clustering, suggestions get assigned to a cluster_id and the UI re-renders
  // with grouped cards. We'll wait for either a "cluster" badge or a fresh re-render.
  await page.waitForTimeout(8_000);  // give the LLM time to respond

  // Re-load to confirm persistence
  await page.reload();
  // Page should still render cleanly
  await expect(page.getByRole('heading', { name: /Suggestions|Sugest/i }).first()).toBeVisible();
});

// ---------------------------------------------------------------------------
// 3. Admin → Meetings → paste raw notes → AI summarize
// ---------------------------------------------------------------------------

test('AI: admin pastes meeting notes → AI summarizes', async ({ page, request }) => {
  test.setTimeout(90_000);
  // Create a meeting via API so the test is deterministic
  const { token } = await loginApi(request, 'admin@condoos.dev', 'admin123');
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };
  const future = new Date(Date.now() + 24 * 3600 * 1000).toISOString();
  const created = await request.post(`${apiURL}/meetings`, {
    headers,
    data: { title: `E2E AI summarize ${Date.now()}`, scheduled_for: future, agenda: 'Testar resumo da IA' },
  });
  expect(created.ok()).toBeTruthy();
  const meetingId = (await created.json()).data.id;

  await browserLogin(page, request, 'admin');
  await page.goto(`/board/meetings/${meetingId}`);

  // Paste raw notes into the textarea
  const notes = `
- Síndico abriu a reunião 20:05.
- Aprovaram a troca do ar do saguão por 4 a 1, contratada Cool Breeze HVAC, R$ 47.000.
- Discutiram carregadores EV — vai esperar segundo orçamento antes de votar.
- Reclamação da esteira #3 da academia — chamado aberto com Fitness Pro.
- Reunião encerrada 21:10.
  `.trim();
  await page.locator('textarea').first().fill(notes);

  // Click Summarize
  await page.getByRole('button', { name: /Summarize|Resumir com IA|Summarize with AI/i }).first().click();

  // Wait for the AI summary card to render (typically takes 5-15s for Claude Haiku)
  // Look for a heading or text indicating the summary succeeded
  await expect(page.getByText(/decisão|decision|summary|resumo|recap/i).first()).toBeVisible({ timeout: 60_000 });
});

// ---------------------------------------------------------------------------
// 4. Admin → Close & AI decision → publishes announcement
// ---------------------------------------------------------------------------

test('AI: admin closes voting → AI writes decision summary + announcement', async ({ page, request }) => {
  test.setTimeout(90_000);
  const { token } = await loginApi(request, 'admin@condoos.dev', 'admin123');
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };

  // Create a fresh proposal in voting state with a couple of votes
  const created = await request.post(`${apiURL}/proposals`, {
    headers,
    data: { title: `E2E decision ${Date.now()}`, description: 'Proposta para validar o fluxo de decisão da IA.', category: 'maintenance', estimated_cost: 12000 },
  });
  const propId = (await created.json()).data.id;
  // Move to voting
  await request.post(`${apiURL}/proposals/${propId}/status`, { headers, data: { status: 'voting' } });
  // Cast a yes vote as admin
  await request.post(`${apiURL}/proposals/${propId}/vote`, { headers, data: { choice: 'yes' } });
  // Cast a yes as resident
  const resident = await loginApi(request, 'resident@condoos.dev', 'resident123');
  await request.post(`${apiURL}/proposals/${propId}/vote`, {
    headers: { Authorization: `Bearer ${resident.token}`, 'Content-Type': 'application/json' },
    data: { choice: 'yes' },
  });

  // Drive the UI: navigate as admin, click "Close & AI decision"
  await browserLogin(page, request, 'admin');
  await page.goto(`/board/proposals/${propId}`);
  // The label may be EN or PT-BR; cover both
  const closeBtn = page.getByRole('button', { name: /Close.*AI decision|Encerrar.*decisão|AI decision/i }).first();
  await expect(closeBtn).toBeVisible({ timeout: 10_000 });
  await closeBtn.click();

  // Wait for the decision summary card to render — look for the AI-generated headline
  await expect(page.getByText(/decisão|decision|aprovada|approved|rationale|justificativa/i).first()).toBeVisible({ timeout: 60_000 });
});

// ---------------------------------------------------------------------------
// 5. Admin → Assembly → AI suggest agenda
// ---------------------------------------------------------------------------

test('AI: admin generates assembly agenda via AI', async ({ page, request }) => {
  test.setTimeout(75_000);
  const { token } = await loginApi(request, 'admin@condoos.dev', 'admin123');
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };

  // Create empty draft assembly
  const future = new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString();
  const created = await request.post(`${apiURL}/assemblies`, {
    headers, data: { title: `E2E AI agenda ${Date.now()}`, kind: 'ordinary', first_call_at: future },
  });
  const assemblyId = (await created.json()).data.id;

  await browserLogin(page, request, 'admin');
  await page.goto(`/board/assemblies/${assemblyId}`);

  // The "Draft with AI" CTA only renders when the agenda is empty
  await page.getByRole('button', { name: /Draft with AI|Redigir com IA|Sugerir pauta/i }).first().click();

  // Wait for at least one agenda item to appear (AI returns 4-6 typically).
  // Items render as a numbered list with `#1`, `#2`… order pills.
  await expect(page.locator('span.font-mono').filter({ hasText: /^#1$/ }).first()).toBeVisible({ timeout: 45_000 });

  // Verify via API that items got persisted
  const detail = await request.get(`${apiURL}/assemblies/${assemblyId}`, { headers });
  const body = (await detail.json()).data;
  expect(body.agenda.length, 'expected ≥1 agenda item from AI draft').toBeGreaterThanOrEqual(1);
});
